# Generated by Django 4.1.1 on 2022-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('itemIndex', models.IntegerField()),
                ('spotX', models.FloatField()),
                ('spotY', models.FloatField()),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
